### ISSUE TITLE
Custom Claim Names are not optional (e.g. USR)

### ISSUE THREAD

**Issue by brettveenstra** [jdemeuse1204/Jot#2]
The claims beyond the Registered Claim Names for JWT (https://tools.ietf.org/html/rfc7519) are being created, even when no value has been provided, such as "usr"

**Comment by jdemeuse1204** [comment]
Thank you @brettveenstra, I am looking into this issue as well.

**Comment by jdemeuse1204** [comment]
@brettveenstra Are you proposing I remove all claims with no value or just the claims that do not match the RFC spec, (rol, usr)

**Comment by brettveenstra** [comment]
@jdemeuse1204 I like the easy path you were making with the JwtToken(jwtTimeOut) ctor but I'd prefer you exclude any non-values from the final Token... perhaps you could add overloads to that ctor path though?  Maybe a custom object that holds Issuer, Audience, etc that gets inspected and claims assigned so you don't have a laundry list of string parameters that could easily get transposed?

**Comment by jdemeuse1204** [comment]
@brettveenstra 

1.  I can definitely do that.  Users will have to use the ClaimExists method before they get the claim, otherwise it will throw an exception because the claim doesnt exist.  That or I can add `bool TryGetClaim<T>(string claimKey, out T claim)`.  Its really the users preference. 

2.  Yeah I was toying with that idea, I ended up doing a dictionary of string/object for flexibility.  I can take this out and make it a custom object, the only thing is that will introduce a breaking change.

**Comment by brettveenstra** [comment]
@jdemeuse1204 - you could look at a dynamic dictionary when referencing those Claims that might not be there, my concerns started in the optimizing the serialization in the JWT as well as the confusion caused by claims existing that were not part of the spec when using the "easy" path

Definitely like a `TryGetClaim<T>` approach too

**Comment by jdemeuse1204** [comment]
@brettveenstra I removed usr and rol from the default claims that are set.  I also added a `TryGetClaim<T>` method as well.  If you want to go in and use your dynamic dictionary idea feel free :).  Am I ok to close this issue?

**Comment by brettveenstra** [comment]
Sounds good to me.  Will submit another PR if I get the chance

**Comment by jdemeuse1204** [comment]
Closing, removed custom claims from default list of claims
